### ISSUE TITLE
HTTPS containers give 404s

### ISSUE THREAD

**Issue by finnjbm** [justmiles/traefik-cloudflare-tunnel#1]
First of all, this project is super cool and I really like it! However, I'm having one major issue. HTTP containers work great, but when I try to enable HTTPS as the traefik entrypoint, I can't get a connection established on the traefik dashboard or on any containers. Just for simplicity, I'll be providing details about the traefik dashboard only as I suspect they all have the same issue.

1. It looks like the DNS records are being properly upserted (my domain is replaced with example.com)
`traefik-cloudflare-tunnel  | time="2022-09-27T19:31:41Z" level=info msg="upserting tunnel" domain=traefik.example.com service="http://traefik:80"`
`cloudflared                | 2022-09-27T19:31:36Z INF Updated to new configuration config="{\"ingress\":[{\"hostname\":\"traefik.example.com\", \"originRequest\":{\"httpHostHeader\":\"traefik.example.com\"}, \"service\":\"http://traefik:80\"}, {\"originRequest\":{\"httpHostHeader\":\"\"}, \"service\":\"http_status:404\"}], \"warp-routing\":{\"enabled\":false}}" version=79`

acme.json also generates so it looks like it's generating the certs correctly.

2. The only errors I can find are the 404s with no other details
from traefiks access.log
`"GET / HTTP/1.1" 404 19 "-" "-" 2 "-" "-" 0ms`
from the browser (just this text):
`404 page not found`

3. Here's thr traefik config (all the potentially relevant parts from the research I've done)
```
commands:
      - --api.insecure=true
      # DNS certgen and TLS stuff
      - --serversTransport.insecureSkipVerify=true
      - --certificatesResolvers.dns-cloudflare.acme.caServer=https://acme-staging-v02.api.letsencrypt.org/directory
      - --certificatesResolvers.dns-cloudflare.acme.email=$DNS_EMAIL
      - --certificatesResolvers.dns-cloudflare.acme.storage=/acme.json
      - --certificatesResolvers.dns-cloudflare.acme.dnsChallenge.provider=cloudflare
      - --certificatesResolvers.dns-cloudflare.acme.dnsChallenge.resolvers=1.1.1.1:53,1.0.0.1:53
      - --certificatesResolvers.dns-cloudflare.acme.email=$DNS_EMAIL
      - --certificatesResolvers.dns-cloudflare.acme.storage=/acme.json
      - --certificatesResolvers.dns-cloudflare.acme.dnsChallenge.provider=cloudflare
      - --certificatesResolvers.dns-cloudflare.acme.dnsChallenge.resolvers=1.1.1.1:53,1.0.0.1:53
      - --entrypoints.https.http.tls.certresolver=dns-cloudflare
      - --entrypoints.https.http.tls.domains[0].main=$DOMAINNAME_CLOUD_SERVER
      - --entrypoints.https.http.tls.domains[0].sans=*.$DOMAINNAME_CLOUD_SERVER
      # entrypoints
       - --entryPoints.traefik.address=:8080
      - --entrypoints.http.address=:80
      - --entrypoints.https.address=:443
```
    
```
labels:
    - "traefik.enable=true"
    - "traefik.http.routers.traefik.entrypoints=https"
    - "traefik.http.routers.traefik.tls=true"
    - "traefik.http.routers.traefik.service=api@internal"
```

The weird thing is, if I add the following label to either traefik or a container:
`- "traefik.http.routers.traefik.tls.certresolver=dns-cloudflare"`
Then it isn't recognized by traefik-cloudflare-tunnel and doesn't upsert. This happens with no errors or indication of something wrong happening. From my understanding of the traefik log, this is also the label that actually makes the container generate the certs using the cert resolver.

If you need any other details, please let me know. I don't want to make you debug my traefik config if it's not an issue with the project, it just appeared to me like this was unique to using this project (based on all the similar fixes I've used from other traefik dashboard 404 quesitons on the internet), so please let me know if it's not. I also am more than happy to implement the fix/figure out the problem, I'm just honestly a little confused on where to start and wondered if you had any guidance or similar issues.

Thanks! Finn

**Comment by justmiles** [comment]
Hi Finn! Glad to see others finding value in this project.

I'm going to start by saying I'm pretty sure this is [working as designed](https://github.com/justmiles/traefik-cloudflare-tunnel/blob/master/main.go#L61), but definitely open to improving it if it should change. That said, the original intent is to let CloudFlare manage both DNS and SSL with Traefik only responsible for routing traffic from the `cloudflared` daemon to the individual containers (over a non-TLS port, eg 80). If your domain is configured under CloudFlare (which I believe it has to be for zero-trust to work) then you don't need to configure Traefik's cert resolver.

You mentioned that `acme.json` is getting the certs so it would appear that your domain is [configured to provision SSL](https://developers.cloudflare.com/cloudflare-one/faq/cloudflare-tunnels-faq/#check-ssltls-encryption-mode)?

What is the `TRAEFIK_ENTRYPOINT` environment variable set to for the `traefik-cloudflare-tunnel` image? Looking at your configs, it should be `TRAEFIK_ENTRYPOINT=http`.

When you start the container you want to route traffic to, start it with the following labels (without any TLS configs):

```
"traefik.enable=true"
"traefik.http.routers.myservice.rule=Host(`myservice.example.com`)"
"traefik.http.routers.myservice.entrypoints=http"
```
