### ISSUE TITLE
Authentication Error

### ISSUE THREAD

**Issue by jan-schaeffer** [justmiles/traefik-cloudflare-tunnel#2]
Hi, 

thank you for this great project. It's exactly what I was looking for and nobody else seems to have implemented this thus far. 

I'm trying to run the example but get `level=fatal msg="unable to pull current tunnel config, Authentication error (10000)"`

Probably I entered the wrong API token, could you please specify what kind of Token I need to generate? 

Best,
Jan

**Comment by justmiles** [comment]
Hi @jan-schaeffer,

That error is thrown when one of these three is incorrect:

1. The `CLOUDFLARE_API_TOKEN`. This is your API token and you can create/obtain one here: https://dash.cloudflare.com/profile/api-tokens
2. The `CLOUDFLARE_ACCOUNT_ID`. Your account ID is a 32 character hash unique to you. After you login to cloudflare, you can find it in the URL here: https://dash.cloudflare.com
3. The `CLOUDFLARE_TUNNEL_ID`. This is the ID of the Cloudflare tunnel. You can create one from the Zero Trust dashboard and navigating to Access -> Tunnels. The ID is under the name.

Hope this helps!

**Comment by jan-schaeffer** [comment]
Thanks for the reply, missed it due to the holidays... what permissions does the API token need?

**Comment by justmiles** [comment]
No worries! It needs these permissions:

- Account -> Cloudflare Tunnel -> Edit
- Account -> Zero Trust -> Edit
- User -> User Details -> Read
- Zone -> DNS -> Edit

**Comment by MarcPartensky** [comment]
Hi could you please include those permissions in the README? It took me way too much time to find those. Thanks for what you do

**Comment by justmiles** [comment]
No problem, I've updated the README.

**Comment by MarcPartensky** [comment]
Thank you so much, this is a great project !
