### ISSUE TITLE
HTTPS - No Entry point found

### ISSUE THREAD

**Issue by ImtiazAliJamil** [justmiles/traefik-cloudflare-tunnel#3]
Hi I tried the project it's working with HTTP perfectly. struggling with https.  Can you please add and HTTPS example if this supports it?

```services:
  traefik:
    image: "traefik:v2.6"
    container_name: "traefik"
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"    

      - "--entryPoints.web.http.redirections.entryPoint.to=websecure"     
      - "--entryPoints.web.http.redirections.entryPoint.scheme=https"    
      - "--entryPoints.web.http.redirections.entrypoint.permanent=true"   
    ports:
      - "80:80"
      - "8080:8080"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  whoami:
    image: "traefik/whoami"
    container_name: "simple-service"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`${DOMAIN_NAME}`)"
      - "traefik.http.routers.whoami.entrypoints=web"

  cloudflared:
    image: cloudflare/cloudflared:2022.5.1
    container_name: cloudflared
    command:
      - tunnel
      - --no-autoupdate
      - run
      - --token=${CLOUDFLARED_TOKEN}

  traefik-cloudflare-tunnel:
    image: "justmiles/traefik-cloudflare-tunnel:latest"
    environment:
      - CLOUDFLARE_API_TOKEN=${CLOUDFLARE_API_TOKEN}
      - CLOUDFLARE_ACCOUNT_ID=${CLOUDFLARE_ACCOUNT_ID}
      - CLOUDFLARE_TUNNEL_ID=${CLOUDFLARE_TUNNEL_ID}
      - CLOUDFLARE_ZONE_ID=${CLOUDFLARE_ZONE_ID}
      - TRAEFIK_SERVICE_ENDPOINT=http://traefik:80
      - TRAEFIK_API_ENDPOINT=http://traefik:8080
      - TRAEFIK_ENTRYPOINT=web,websecure
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    ports:
#      - 8000:8000
      - 9443:9443
      - 9000:9000 # for http
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    # networks:
    #   proxy:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portainer.entrypoints=web"
      - "traefik.http.routers.portainer.rule=Host(`portainer.example.com`)"
#      - "traefik.http.middlewares.portainer-https-redirect.redirectscheme.scheme=https"
#      - "traefik.http.routers.portainer.middlewares=portainer-https-redirect"
#      - "traefik.http.routers.portainer-secure.entrypoints=websecure"
#      - "traefik.http.routers.portainer-secure.rule=Host(`portainer.example.com`)"
#    #   - "traefik.http.routers.portainer-secure.tls=true"
#      - "traefik.http.routers.portainer-secure.service=portainer"
#      - "traefik.http.services.portainer.loadbalancer.server.port=9443"
#    #   - "traefik.docker.network=proxy"
volumes:
  portainer_data:

# networks:
#   proxy:
#     external: true`
Thanks,
```

**Comment by justmiles** [comment]
It's important to keep in mind that when you're using Cloudflare tunnels TLS terminates on Cloudflare, not on Traefik. See here as well https://github.com/justmiles/traefik-cloudflare-tunnel/issues/1#issuecomment-1270213749.

If your goal is to encrypt the internal traffic as well, then I would expect your backend service (whatever Traefik is pointing to) to have its own certificate and at that point you should just point cloudflared directly at the backend service.

Hope this helps and happy to elaborate further if it's helpful.

**Comment by idoodler** [comment]
Services like Portainer per default only expose port 9443 which is the HTTPS port of Portainer. Yes you can set it up directly using Cloudflare or use the HTTP port instead, tho isn't this project about automation?

It would be perfect if it enables the "No TLS Verify" flag and also sets the "Origin Server Name" to the Domain.

**Comment by justmiles** [comment]
Yes, Portainer does generate its own certificate and communication between the browser and Portainer should be secured via TLS but the default certificate is only necessary if there's no reverse proxy. Portainer's [documentation for setting up Traefik ](https://docs.portainer.io/advanced/reverse-proxy/traefik) shows to use the non-HTTPS ports exposed by Portainer and to terminate TLS on Traefik itself.

If you set up Portainer using Traefik following those docs, this is what that would look like:

```mermaid
flowchart LR
    A[Browser] <-->|Encrypted| D[Traefik]
    D <-->|Unencrypted| E[Portainer]
```

And if you introduce Cloudflare into the mix, here's what it would look like:

```mermaid
flowchart LR
    A[Browser] <-->|Encrypted| B((Cloudflare))
    B <-->|Encrypted| C{{cloudflared}}
    C <-->|Unencrypted| D[Traefik]
    D <-->|Unencrypted| E[Portainer]
```

It is certainly possible to _also_ encrypt the traffic between `cloudflared` and `traefik` and even the traffic between `traefik` and `portainer`, but that's an edge case I've only seen required in highly regulated environments. Understanding the above if we still want to ensure that downstream traffic is encrypted I can start scoping the effort, but keep in mind this would only be able to configure the connectivity between `cloudflared` and `traefik`. The user would need to configure the encryption between `traefik` and `portainer`.
