### ISSUE TITLE
ARM Support

### ISSUE THREAD

**Issue by A2va** [justmiles/traefik-cloudflare-tunnel#4]
Hi there! 

Your project is very useful, but since I'm using a Raspberry. I'd like to see support for an ARM image.

By the way, I noticed that your fork of the cloudflare library can maybe be replaced by a newer version, because they have added some features related to the tunnels:
https://pkg.go.dev/github.com/cloudflare/cloudflare-go#Tunnel

**Comment by Roxedus** [comment]
The project builds just fine on arm, I tested this when I played with docker bake in a [repo](https://github.com/Roxedus/pipelines/blob/main/traefik-cloudflare-tunnel-bake.hcl), which then gets pushed to ghcr for the same repo.

**Comment by A2va** [comment]
Thank you for providing the image build. However, I am having trouble pulling your image from github:
```
> docker pull ghcr.io/roxedus/pipelines:traefik-cloudflare-tunnel-latest
Error response from daemon: Head "https://ghcr.io/v2/roxedus/pipelines/manifests/traefik-cloudflare-tunnel-latest": denied: denied
```

**Comment by justmiles** [comment]
For sure, I'll setup a build pipeline and add an ARM build.

**Comment by justmiles** [comment]
I've added ARM to the build. There's a docker image available too!
