### ISSUE TITLE
CNAME record with that host already exists

### ISSUE THREAD

**Issue by smagicld** [justmiles/traefik-cloudflare-tunnel#5]
Hi

Just setup your docker for ZeroTrust tunnels update. It's exactly what I was looking for. Thanks!
Unfortunately there is one Issue (at least on my setup):

when the CF Tunnel Config is empty / and the DNS entries does not exist - everything is updated correctly.

Then, If I shutdown your docker image AND start it again, the service is trying to re-register the domains.
CF if giving then error about existing DNS Entries.
Below sample Log entry:
`time="2024-04-06T06:01:36Z" level=info msg="changes detected"
time="2024-04-06T06:01:36Z" level=info msg="upserting tunnel" domain=traefik.xxxxx.xx service="http://traefik:80"
time="2024-04-06T06:01:36Z" level=info msg="upserting tunnel" domain=whoami.xxxxx.xx service="http://traefik:80"
time="2024-04-06T06:01:37Z" level=info msg="tunnel config updated"
time="2024-04-06T06:01:39Z" level=fatal msg="unable to create DNS record, An A, AAAA, or CNAME record with that host already exists. For more details, refer to <https://developers.cloudflare.com/dns/manage-dns-records/troubleshooting/records-with-same-name/>. (81053)"`

is this something on my side or the code needs an check if domain exists before re-registrating?

**Comment by justmiles** [comment]
It should be doing an upsert (update or insert). It's definitely checking if the record is already there, and if not, creating it. I wonder if it doesn't have permissions to read the current record.

You can see [its attempting to read it here](https://github.com/justmiles/traefik-cloudflare-tunnel/blob/master/main.go#L176), but I don't see an error message from the read failing, though. It seems like it's "successfully" reading zero records for that domain name which makes me think it might be permission related. eg, its allowed to run GetDNSRecords, but the results are limited.

**Comment by justmiles** [comment]
Closing stale / can't re-produce. If this is still an issue let me know!
